### ISSUE TITLE
wrong parameters in `Object.keys(dup.s).forEach()`

### ISSUE THREAD

**Issue by jacobbubu** [gundb/port#1]
https://github.com/gundb/port/blob/master/dup.js#L10

might be:
``` js
  Object.keys(dup.s).forEach(function(id) {
    var time = dup.s[id];
    if (opt.age > ((+new Date()) - time)){ return }
    delete dup.s[id];
 });
```

**Comment by amark** [comment]
@jacobbubu GOOOOOOOOD catch!!!

Fixing in my current working branch `manhattan`, so this fix will go out in the next NPM publish.

**Comment by amark** [comment]
Oh! This is in the `porting gun talk` repo. Ah, this makes more sense, I'll see if I can edit it inline.
